### ISSUE TITLE
Outdated mirrors or mirror list

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/internet2-repo#1]
The I2 repo mirror list at http://software.internet2.edu/rpms/el6/mirrors-Toolkit-Internet2 is either outdated at least one of its mirror is not up to date.

This particular host has not been updated since May 5th: http://mirror.chpc.utah.edu/pub/software.internet2.edu/rpms/el6/i386/main/repodata/

See: https://github.com/perfsonar/bundles/issues/4

**Comment by arlake228** [comment]
I temporarily removed this URL from the mirror list. I am also trying to track down the owner of the mirror.

**Comment by arlake228** [comment]
Utah fixed their mirror. Their rsyncs were mistakenly getting blocked by the I2 server. I have added them back to the mirror list.
