### ISSUE TITLE
ftp.sunet.se needs to be removed from mirror list

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/internet2-repo#2]
The perfSONAR mirror list hosted at I2 is outdated, the ftp.sunet.se host is not replicating our repository anymore.  We should remove it.

Initially [reported on perfsonar-user list](https://lists.internet2.edu/sympa/arc/perfsonar-user/2019-09/msg00046.html).

**Comment by arlake228** [comment]
It has been removed.
